dist: xenial
language: php
php:
  - 7.0
services:
  - mysql
script:
  - gem install travis
  - sudo apt-get install git -y
  - cd ~
  - git clone https://github.com/MrSpy0x22/test_ci.git
  - cd test_ci
  - mysql -u root < prepare_mysql.sql
  - php -l index.php
branches:
  only:
    - master
