dist: xenial
language: php
php:
  - 7.2
services:
  - mysql
before_install:
  - sudo apt-get install git -y  
  - cd ~
  - git clone https://github.com/MrSpy0x22/test_ci.git
  - cd test_ci
  - openssl aes-256-cbc -K $encrypted_383bc2ea2d21_key -iv $encrypted_383bc2ea2d21_iv -in deploy_rsa.enc -out deploy_rsa -d
  - chmod 600 deploy_rsa
  - eval "$(ssh-agent -s)"
  - ssh-add deploy_rsa
  - echo $encrypted_4455a229d80f_key >> ~/.ssh/known_hosts
before_script:
  - wget -O phpunit https://phar.phpunit.de/phpunit-8.phar
  - chmod +x phpunit
  - ./phpunit --version
  - mysql -e "CREATE DATABASE ci_test"
  - mysql -u root ci_test < prepare_mysql.sql
script:
  - php -l index.php
  - ssh -o "StrictHostKeyChecking no" "$SSH_HOST" -p7878 -l "$SSH_USER"
after_success:
  - rsync -av --delete -e -p6883 ssh "$SSH_USER"@"$SSH_HOST":/var/www/html/test_ci/
branches:
  only:
    - master
addons:
  ssh_known_hosts: 77.55.217.32
env:
  global:
    - SSH_USER="travis_deployer"
    - SSH_HOST="77.55.217.32"