dist: xenial
language: php
php:
  - 7.0
services:
  - mysql
before_script:
  - sudo apt-get install git -y  
  - cd ~
  - git config --global user.name "MarSpy"
  - git config --global user.email marcin22x@gmail.com
script:
  - git clone https://github.com/MrSpy0x22/test_ci.git
  - cd test_ci
  - mysql -e "CREATE DATABASE ci_test"
  - mysql -u root ci_test < prepare_mysql.sql
  - php -l index.php
after_success:
branches:
  only:
    - master