dist: xenial
language: php
php:
  - 7.0
services:
  - mysql
script:
  - sudo apt-get install git -y
  - cd ~
  - git clone https://github.com/MrSpy0x22/test_ci.git
  - cd test_ci
  - php -l index.php
branches:
  only:
  - master
notifications:
  email: false
