dist: xenial
language: php
php:
  - 7.2
services:
  - mysql
before_install:
  - openssl aes-256-cbc -K $encrypted_4455a229d80f_key -iv $encrypted_4455a229d80f_iv -in SSH_KEY_NAME.enc -out SSH_KEY_NAME -d
before_script:
  - composer install --prefer-source
  - npm install
  - wget -O phpunit https://phar.phpunit.de/phpunit-8.phar
  - chmod +x phpunit
  - ./phpunit --version
  - sudo apt-get install git -y  
  - cd ~
  - git clone https://github.com/MrSpy0x22/test_ci.git
  - cd test_ci
  - mysql -e "CREATE DATABASE ci_test"
  - mysql -u root ci_test < prepare_mysql.sql
script:
  - php -l index.php
after_success:
  - echo "${SFTP_PASSWORD}" | base64 --decode >/tmp/sftp_rsa
  - echo "${SFTP_USER}" | base64 --decode >/tmp/sftp_rsa
  - curl --ftp-create-dirs -T index.php --key /tmp/sftp_rsa sftp://${SFTP_USER}:${SFTP_PASSWORD}@polskiegw.pl/testci/index.php
  - curl --ftp-create-dirs -T style.css --key /tmp/sftp_rsa sftp://${SFTP_USER}:${SFTP_PASSWORD}@polskiegw.pl/testci/style.css
branches:
  only:
    - master
addons:
  ssh_known_hosts: polskiegw.pl