dist: xenial
language: php
php:
  - 7.0
services:
  - mysql
before_install:
  - mysql -e "CREATE DATABASE IF NOT EXISTS ci_test;GRANT SELECT, ALTER, CREATE, UPDATE, INSERT, DELETE, DROP ON ci_test.* TO 'test_ci'@'localhost';FLUSH PRIVILEGES;"
  - mysql -e "USE ci_test; CREATE TABLE IF NOT EXISTS messages(msg_id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,uname VARCHAR(32) NOT NULL,timestamp TIMESTAMP NOT NULL,message TEXT(256) NOT NULL,PRIMARY KEY(msg_id));"
script:
  - sudo apt-get install git -y
  - cd ~
  - git clone https://github.com/MrSpy0x22/test_ci.git
  - cd test_ci
  - php -l index.php
branches:
  only:
  - master
notifications:
  email: false
