dist: xenial
language: php
php:
  - 7.0
services:
  - mysql
script:
  - sudo apt-get update
  - sudo apt-get upgrade
  - sudo apt-get install git -U
  - cd ~
  - git clone https://github.com/MrSpy0x22/test_ci.git
  - cd test_ci
branches:
  only:
  - master
notifications:
  email: false
