dist: xenial
language: php
php:
  - 7.0
services:
  - mysql
before_install:
  - mysql -e "CREATE DATABASE IF NOT EXISTS $[DB_NAME];GRANT SELECT, ALTER, CREATE, UPDATE, INSERT, DELETE, DROP ON $[DB_NAME].* TO '$[DB_USER]'@'localhost'IDENTIFIED BY '$[DB_PASSWD]';FLUSH PRIVILEGES;"
  - mysql -e "USE $[DB_NAME]; CREATE TABLE IF NOT EXISTS messages(msg_id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,uname VARCHAR(32) NOT NULL,timestamp TIMESTAMP NOT NULL,message TEXT(256) NOT NULL,PRIMARY KEY(msg_id));"
script:
  - sudo apt-get install git -y
  - cd ~
  - git clone https://github.com/MrSpy0x22/test_ci.git
  - cd test_ci
  - php -l index.php
branches:
  only:
    - master
env:
  - DB_PASSWD=*
  - DB_NAME=*
  - DB_NAME=*
notifications:
  email: false
