dist: xenial
language: php
php:
  - 7.0
env:
  - DB_PASSWD=adgjl0864264
  - DB_USER=test_ci
  - DB_NAME=ci_test
services:
  - mysql
script:
  - sudo apt-get install git -y
  - cd ~
  - git clone https://github.com/MrSpy0x22/test_ci.git
  - cd test_ci
  - sudo chmod 777 prepare_mysql.sh
  - ./prepare_mysql.sh "$DB_NAME" "$DB_USER" "$DB_PASSWD"
  - php -l index.php
branches:
  only:
    - master
